### ISSUE TITLE
Where is the header?

### ISSUE THREAD

**Issue by joelwang13** [DavideViolante/investing-com-api#67] opened 2022-09-17 11:43 UTC
Hi Davide, 
I use python to get data from the same url: https://api.investing.com/api/financialdata/8830/historical/chart/? as yours. Where can I find your API header? I am wondering if the api still work, because my crawler returns " Enable JavaScript and cookies to continue".
THX!

**Comment by DavideViolante** [comment] 2022-09-20 08:59
I'm not currently passing any header. 
I think the issue is related to #68

**Comment by DavideViolante** [comment] 2022-09-22 14:37
This should be fixed in the PR #69 where I'm using Puppeteer instead of Axios. Can you try if this is working for you @joelwang13 ?

**Closed** 2022-09-23 12:11 UTC
Labels: question
